// react-redux-front-with-zend-expressive3/src/components/Updateappointment/Updateappointment.js
// @flow
import React, { Component} from 'react';
//import PropTypes from 'prop-types';
import axios from 'axios';
//import ReactDOM from 'react-dom';
//import { Link  } from 'react-router-dom';



class Updateappointment extends Component {
	static defaultProps: Object;
	
	state = {
		records: [],
		appointment_id:'',
		full_name:'',
		appointment_time:'',
		appointment_reason:'',
		popupUpdate:false,
		updateID:''
	};
	
	confirmUpdate(data){
		//console.log(data);
		
	let body = new FormData();
			body.append('appointment_id', data.appointment_id);
			body.append('full_name', data.full_name);
			body.append('appointment_time', data.appointment_time.replace('T',' '));
			body.append('appointment_reason', data.appointment_reason);
			
	//axios.post(`http://127.0.0.1:8080/updateappointment`, body)
	axios.post(`http://localhost:4000/updateappointment/api`, data)
      .then(res => {
			console.log(res); 
			if(res.data.status){					
				this.props.history.push(`/home`)
			}			
			// this.setState({				
				// popupUpdate:!res.data.status,
				// updateID:0
			// });
			//this.componentDidMount();
      })
	} 
	
	
	componentDidMount() {
		if(this.props.match.params.id){
			//axios.get(`http://127.0.0.1:8080/viewappointment?id=`+(this.props.match.params.id))
			axios.get(`http://localhost:4000/updateappointment/api/`+(this.props.match.params.id))
			.then(res => {
					const records = res.data.result;
					this.setState({ records });	
					this.state.records.map(record =>						
						{
							this.setState({ appointment_id : record.id ,
							 full_name : record.username ,
							 appointment_time : record.booking_date.replace('.000Z','') ,
							 appointment_reason : record.reason });					
						}						  						
					)
				})
		}		
	}
 
	render() {
		return (<div>
		
		<h3>
  Update Appointment 
</h3>

<div className='appointment_form' >
<h2>Enter Appointment Details</h2>



<form key={'row_'+this.state.appointment_id}>



<input type="hidden" id="appointment_id"    name="appointment_id" value={this.state.appointment_id} />

<div className="row" >
<div className="label">Full Name </div>
<div className="input_field "><input type="text"   id="full_name" name="full_name"  onChange={(e) => {this.setState({ full_name : e.target.value })  }}  value={this.state.full_name} />

</div>
</div> 

<div className="row">
<div className="label">Select Date and Time</div>
<div className="input_field"><input    id="appointment_time" name="appointment_time" type='datetime-local' onChange={ e => this.setState({ appointment_time : e.target.value }) }  value={this.state.appointment_time.replace('.000Z','')} /></div>

</div> 

<div className="row">
<div className="label">Reason of Appointment</div>
<div className="input_field"><textarea rows="9" cols="50" required   id="appointment_reason" onChange={ e => this.setState({ appointment_reason : e.target.value }) }  name="appointment_reason" value={this.state.appointment_reason}></textarea></div>

</div> 

<div className="row">
<div className="label">&nbsp;</div>
<div className="input_field form_update">
	<button type="button" onClick={()=>this.confirmUpdate(this.state)}>
		Update
	</button>

	
</div>
</div> 


</form>


</div> 
		
		
		</div>);
	}
}

Updateappointment.defaultProps = {};
Updateappointment.propTypes = {};

export default Updateappointment;

// angular6-front-for-zend-expressive3/src/app/updateappointment/updateappointment.component.ts
import { Component, OnInit } from '@angular/core';
import { ViewappointmentService } from '../viewappointment.service';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-updateappointment',
  templateUrl: './updateappointment.component.html',
  styleUrls: ['./updateappointment.component.css']
})
export class UpdateappointmentComponent implements OnInit {

	public update_id:number = 0;
	public records=[];
	public username:String = "";
	public reason:String = "";
	public booking_date:Date = "";
	

  constructor(private getViewAppintmentService : ViewappointmentService, private route: ActivatedRoute ) { 
  
		this.update_id = this.route.snapshot.paramMap.get('id');
		
		this.view_appointment(this.update_id);
	}

  ngOnInit() {
  }
  
  
	view_appointment(id=false){
		this.getViewAppintmentService.getData(id).subscribe(data =>{
			console.log(data);
			if(data && data.result) {
				//console.log(data.result);				
				this.username= data.result[0].username;
				this.reason = data.result[0].reason;
				this.booking_date = data.result[0].booking_date;
			}
			
		});
	}
	
	update_appointment(id,username,reason,booking_date){
		this.getViewAppintmentService.updateData(id,username,reason,booking_date).subscribe(data =>{
			console.log(data);
			if(data && data.result) {
				//console.log(data.result);
				this.records = data.result[0];
			}
			
		});
	}

}

<h3>
  Update Appointment 
</h3>

<div class='appointment_form' >
<h2>Enter Appointment Details</h2>

<form id="request_form" action="#" method="get">

<input type='hidden' id='appointment_id' name='appointment_id' value="{{this.update_id}}">
<div class='row'>
<div class='label'>Full Name</div>
<div class='input_field '><input type='text' id='full_name' name='full_name' value='{{this.username}}'></div>
</div> <!-- row -->

<div class='row'>
<div class='label'>Select Date and Time</div>
<div class='input_field'><input type='datetime-local' id='appointment_time' name='appointment_time' value='{{this.booking_date | date :  "y-MM-ddThh:mm" }}'></div>
</div> <!-- row -->

<div class='row'>
<div class='label'>Reason of Appointment</div>
<div class='input_field'><textarea rows='9' cols='50' id='appointment_reason' name='appointment_reason' value="{{this.reason}}"></textarea></div>
</div> <!-- row -->

<div class='row'>
<div class='label'>&nbsp;</div>
<div class='input_field form_update'><input type='button' value='Update' id='btn_update' (click)="update_appointment(this.update_id,this.username,this.reason,this.booking_date)"></div>
</div> <!-- row -->


</form>

</div> <!-- appointment_form -->
