// react-cli-front-with-zend-expressive3/src/components/Updateappointment/Updateappointment.js
// @flow
import React, { Component} from 'react';
import PropTypes from 'prop-types';
import axios from 'axios';
import ReactDOM from 'react-dom';
import { Link } from 'react-router-dom';


class Updateappointment extends Component {
	static defaultProps: Object;
	
	state = {
		records: []
	};
	
	
	
	componentDidMount() {
		if(this.props.match.params.id){
			axios.get(`http://127.0.0.1:8080/viewappointment?id=`+(this.props.match.params.id))
			.then(res => {
					const records = res.data.result;
					this.setState({ records });			
				})
		}		
	}
 
	render() {

		
		return (<div>
		
		<h3>
  Update Appointment 
</h3>

<div className='appointment_form' >
<h2>Enter Appointment Details</h2>
{ this.state.records.map(record => 
<form key={'row'+record.id}>



<input type="hidden" id="appointment_id"    name="appointment_id" value={record.id} />

<div className="row" >
<div className="label">Full Name </div>
<div className="input_field "><input type="text"   id="full_name" name="full_name" value={record.username} />

</div>
</div> 

<div className="row">
<div className="label">Select Date and Time</div>
<div className="input_field"><input type="text"   id="appointment_time" name="appointment_time" value={record.booking_date} /></div>

</div> 

<div className="row">
<div className="label">Reason of Appointment</div>
<div className="input_field"><textarea rows="9" cols="50" required   id="appointment_reason" name="appointment_reason" value={record.reason}></textarea></div>

</div> 

<div className="row">
<div className="label">&nbsp;</div>
<div className="input_field form_update">
	<button type="submit" >
		Update
	</button>

	<button type="button" >
		Reset
	</button>
</div>
</div> 


</form>
)}
</div> 
		
		
		</div>);
	}
}

Updateappointment.defaultProps = {};
Updateappointment.propTypes = {};

export default Updateappointment;

// angular6-front-for-zend-expressive3/src/app/updateappointment/updateappointment.component.ts
import { Component, OnInit } from '@angular/core';
import { ViewappointmentService } from '../viewappointment.service';
import { ActivatedRoute, Router } from '@angular/router';
import { NgForm } from '@angular/forms';

@Component({
  selector: 'app-updateappointment',
  templateUrl: './updateappointment.component.html',
  styleUrls: ['./updateappointment.component.css'],
  
})
export class UpdateappointmentComponent implements OnInit {

	public appointment_id:number;	
	public full_name:String;
	public appointment_reason:String;
	public appointment_time:Date ;	


	constructor(private getViewAppintmentService : ViewappointmentService, private route: ActivatedRoute, private router: Router ) { 
		if(this.route.snapshot.paramMap.get('id')){
			this.appointment_id = this.route.snapshot.paramMap.get('id');
		
			this.view_appointment(this.appointment_id);
		}
	}

	ngOnInit() {
		
	}  
  
	view_appointment(id=false){
		this.getViewAppintmentService.getData(id).subscribe(data =>{
			//console.log(data);
			if(data && data.result) {
				//console.log(data.result);				
				this.full_name= data.result[0].username;
				this.appointment_reason = data.result[0].reason;
				this.appointment_time = data.result[0].booking_date;
			}
			
		});
	}
	
	update_appointment(id,username,reason,booking_date){
		this.getViewAppintmentService.updateData(id,username,reason,booking_date).subscribe(data =>{
			//console.log(data);
			if(data && data.result) {
				console.log(data.result);
				if(data.result){
					//self.router.navigate(['/home']);
					this.router.navigate(['/home']);
				}
			}
			
		});
	}
	
	onSubmit(form: NgForm) {
		if (form.valid) {
		 // console.log(form.value.appointment_id);
		  this.update_appointment(form.value.appointment_id,
		  form.value.full_name,
		  form.value.appointment_reason,
		  form.value.appointment_time)
		}
	}

}

<h3>
  Update Appointment 
</h3>

<div class='appointment_form' >
<h2>Enter Appointment Details</h2>

<form #newUserForm="ngForm" (ngSubmit)="onSubmit(newUserForm)">

<input type='hidden' id='appointment_id'  [(ngModel)]="appointment_id"  name='appointment_id' value="{{this.appointment_id}}">

<div class='row'>
<div class='label'>Full Name</div>
<div class='input_field '><input type='text' required [(ngModel)]="full_name"  id='full_name' name='full_name' value='{{this.full_name}}'>

</div>
</div> <!-- row -->

<div class='row'>
<div class='label'>Select Date and Time</div>
<div class='input_field'><input type='text'  [(ngModel)]="appointment_time" id='appointment_time' name='appointment_time' value='{{this.appointment_time | date :  "y-MM-dd hh:mm:ss" }}'></div>

</div> <!-- row -->

<div class='row'>
<div class='label'>Reason of Appointment</div>
<div class='input_field'><textarea rows='9' cols='50' required [(ngModel)]="appointment_reason"  id='appointment_reason' name='appointment_reason' value="{{this.appointment_reason}}"></textarea></div>

</div> <!-- row -->

<div class='row'>
<div class='label'>&nbsp;</div>
<div class='input_field form_update'>
	<button type="submit" [disabled]="!newUserForm.form.valid">
		Update
	</button>

	<button type="button" (click)="newUserForm.reset()">
		Reset
	</button>
</div>
</div> <!-- row -->


</form>

</div> <!-- appointment_form -->
