// angular6-front-for-zend-expressive3/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ViewappointmentService } from '../viewappointment.service';

@Component({
	selector: 'app-home',
	templateUrl: './home.component.html',
	styleUrls: ['./home.component.css']
})

export class HomeComponent implements OnInit {

	records = [];	
	fixrecord = {};
	public show_news:boolean = false;
    public buttonName:any = 'Show News';
	public show_delete:boolean = false;
	public delete_id:number = 0;	
	
	
	constructor(private getViewAppintmentService : ViewappointmentService ) { 
		this.delete_id= 0;
	
	}

	ngOnInit() {
		
		this.fixrecord = this.getViewAppintmentService.getData2();
		
		this.view_appointment();
		
	}
	
	view_appointment(id=false){
		this.getViewAppintmentService.getData(id).subscribe(data =>{
			console.log(data);
			if(data && data.result) {
				//console.log(data.result);
				this.records = data.result;
			}
			
		});
	}
	
	toggle() {
		this.show_news = !this.show_news;

		// CHANGE THE NAME OF THE BUTTON.
		if(this.show_news)  
		  this.buttonName = "Hide News";
		else
		  this.buttonName = "Show News";
	}
	
	delete_appointment(id) {
		this.show_delete= true;		
		this.delete_id = id;
		
		this.getViewAppintmentService.deleteData(id).subscribe(data =>{
			console.log(data);
			if(data && data.result) {
				//console.log(data.result);
				this.show_delete = !data.result;
				this.view_appointment();
			}			
		});
		// CHANGE THE NAME OF THE BUTTON.		
	}

}




<h3>
   Appointment List
</h3>

<div class='view_appointments records' >
	<div class="row record reocrd-bold">
	<div class="col-md-2">Name</div>
	<div class="col-md-3">Reason</div>
	<div class="col-md-2">Booking Date</div>
	<div class="col-md-2">End Time</div>
	<div class="col-md-2">Action</div>
	</div>
	<div *ngFor='let rowset of records'>	
		<div class="row record" >
				  <div class="col-md-2">{{rowset.username}}</div>
				  <div class="col-md-3">{{rowset.reason}}</div>
				  <div class="col-md-2">{{rowset.booking_date}}</div>
				  <div class="col-md-2">{{rowset.end_time}}</div>
				  
				  <div  class="col-md-1 icon" alt="Edit appointment" title="Edit appointment" id="edit_{{rowset.id}}" ><a class="fa fa-pencil-square-o" aria-hidden="true" routerLink="/updateappointment/{{rowset.id}}">Edit </a></div>
				  
				  <div  class="col-md-1 icon" alt="Cancel appointment" title="Cancel appointment" id="cancel_{{rowset.id}}" ><a class="fa fa-times" aria-hidden="true" (click)="show_delete=true; delete_id=rowset.id;"> Delete  </a></div>
		</div>
	</div>			  
</div> <!-- view_appointments -->

<button (click)="toggle()" id="bt">
    {{buttonName}}
</button>




<div class='press_release popup' *ngIf="show_news">
<h2>Group health Press Release:</h2>
	<div>
	© 2005 - by Rsystems Ltd. All rights reserved.
		<div>
			New version launch by August'2018!
		</div>
	</div>
</div>

<div class='delete_form popup' *ngIf="show_delete">
<h2>Delete Appointment Details</h2>
	<div>
	Are you sure to delete  Appointment No. {{this.delete_id}}?
		<div>
			<button (click)="delete_appointment(this.delete_id)" id="bt_yes">
				Yes 
			</button>
			<button (click)="show_delete=false" id="bt_no">
				No
			</button>
		</div>
	</div>
</div> <!-- appointment_form -->

// react-redux-front-with-zend-expressive3/src/components/Home/Home.js
// @flow
import React, { Component} from 'react';
//import PropTypes from 'prop-types';
import axios from 'axios';

//import ReactDOM from 'react-dom';
import { Link } from 'react-router-dom';
import Componentnameslider from '../../components/Componentnameslider';
//import Bookappointment from './components/Bookappointment';

class Home extends Component {
	static defaultProps: Object;
	
	state = {
		records: [],
		popupNews: false,
		popupdelete: false,
		deleteID: 0,
		rangeVal: 6
	};
	
	popupPressRelease(){		
		this.setState({
			popupNews:!this.state.popupNews
		})	
	}
	
	showDelete(id){		
		this.setState({
			popupdelete:true,
			deleteID:id
		})	
	}
	
	
	
	confirmDelete(id){		
	let body = new FormData();
			body.append('id', id);
	axios.post(`http://127.0.0.1:8080/deleteappointment`, body)
      .then(res => {
			console.log(res);        
			this.setState({
				popupdelete:!res.data.status,
				deleteID:0
			});
			this.componentDidMount();
      })
	}  
	
	hideDelete(){		
		this.setState({
			popupdelete:false,
			deleteID:0
		})	
	}
	  
	componentDidMount() {
	axios.get(`http://127.0.0.1:8080/viewappointment`)
	.then(res => {
			const records = res.data.result;
			this.setState({ records });			
		})
	}
	
	constructor(props) {
		super(props);
			
		this.updateRange1 = this.updateRange1.bind(this);
	  }
	  
	updateRange1(val) {
		this.setState({
		  rangeVal: val
		})
	  }
	  
	  milibhagat(id){
		  return id=6;
	  }
 
	render() {
		const { rangeVal } = this.state;
		return (
		<div>		
		<Componentnameslider range={rangeVal} kamli={this.milibhagat} updateRange2={this.updateRange1}/>
		<h3>
   Appointment List
</h3>	
		
		
<div className='view_appointments records' >
	<div className="row record reocrd-bold">
	<div className="col-md-2">Name</div>
	<div className="col-md-3">Reason</div>
	<div className="col-md-2">Booking Date</div>
	<div className="col-md-2">End Time</div>
	<div className="col-md-2">Action</div>
	</div>
	<div >	
	
	{ this.state.records.map(record => 
	
		<div className="row record" key={'row'+record.id}>
				  <div className="col-md-2">{record.username}</div>
				  <div className="col-md-3">{record.reason}</div>
				  <div className="col-md-2">{record.booking_date}</div>
				  <div className="col-md-2">{record.end_time}</div>
				  
				  <div  className="col-md-1 icon" alt="Edit appointment" title="Edit appointment"  >
					<Link  to={`/updateappointment/${record.id}`} className="current">Edit</Link>
				  </div>
				  
				  <div  className="col-md-1 icon" alt="Cancel appointment" title="Cancel appointment"  >
					<span  style={{cursor:'pointer'}} onClick={()=>this.showDelete(record.id)}
					>Delete</span>				  
				  </div>
		</div>
	)}
	
	</div>			  
</div> 

<button onClick={()=>this.popupPressRelease()} id="bt" >
    Press Release 
</button>



{this.state.popupNews?
<div className='press_release popup' >
<h2>Group health Press Release: </h2>
	<div>
	© 2005 - by Rsystems Ltd. All rights reserved.
		<div>
			New version launch by August'2018!
		</div>
	</div>
</div>
:null}

{this.state.popupdelete?
<div className='delete_form popup' >
<h2>Delete Appointment Details</h2>
	<div>
Are you sure to delete  Appointment No. {this.state.deleteID}?
		<div>
			<button  onClick={()=>this.confirmDelete(this.state.deleteID)} id="bt_yes">
				Yes 
			</button>
			<button  onClick={()=>this.hideDelete()} id="bt_no">
				No
			</button>
		</div>
	</div>
</div> 
:null}


</div>
		
		);
	}
}

Home.defaultProps = {};
Home.propTypes = {};

export default Home;
