// react-redux-front-with-zend-expressive3/src/components/Bookappointment/Bookappointment.js
// @flow
import React, { Component} from 'react';
//import PropTypes from 'prop-types';
import axios from 'axios';
//import ReactDOM from 'react-dom';
//import { Link  } from 'react-router-dom';

class Bookappointment extends Component {
	static defaultProps: Object;
	
	state = {
		records: [],		
		full_name:'',
		appointment_time:'',
		appointment_reason:'',
		popupAdd:'',
		createID:'',
	};
	
	componentWillUnmount(){
		this.setState({ full_name : '' });
		this.setState({ appointment_time : '' });
		this.setState({ appointment_reason : '' });
	}
	
	bookAppointment(){
		if(this.state.full_name.value){
		let body = new FormData();			
				body.append('full_name', this.state.full_name.value);
				body.append('appointment_time', this.state.appointment_time.value);
				body.append('appointment_reason', this.state.appointment_reason.value);
				
		axios.post(`http://127.0.0.1:8080/createappointment`, body)
		  .then(res => {
				console.log(res); 
				if(res.data.status){
					this.setState({				
						popupAdd:!res.data.status,
						createID:0
					});						
					this.props.history.push(`/`)
				}			
							
		  })
		}
	} 
 
	render() {
		return (
		<div>
		<h3>
  Book Appointment 
</h3>

<div className="appointment_form" >
<h2>Enter Appointment Details</h2>

<form >

<div className="row">
<div className="label">Full Name</div>
<div className="input_field"><input type='text'  ref={(input) => this.state.full_name = input}  id='full_name' name='full_name'   />

</div>
</div> 

<div className='row'>
<div className='label'>Select Date and Time</div>
<div className='input_field'><input type='text'   name="appointment_time" id='appointment_time' ref={(input) => this.state.appointment_time = input}  /></div>

</div> 

<div className='row'>
<div className='label'>Reason of Appointment</div>
<div className='input_field'><textarea  ref={(input) => this.state.appointment_reason = input} rows='9' cols='50' id='appointment_reason' name='appointment_reason'  /></div>

</div> 

<div className='row'>
<div className='label'>&nbsp;</div>
<div className='input_field form_update'>
	 <button type="button" onClick={()=>this.bookAppointment()}>Submit</button>
</div>
</div> 


</form>

</div> 
</div>		
		);
	}
}

Bookappointment.defaultProps = {};
Bookappointment.propTypes = {};

export default Bookappointment;

// angular6-front-for-zend-expressive3/src/app/bookappointment/bookappointment.component.ts
import { Component, OnInit } from '@angular/core';
import { ViewappointmentService } from '../viewappointment.service';
import { ActivatedRoute, Router } from '@angular/router';
import { FormGroup, FormControl, FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-bookappointment',
  templateUrl: './bookappointment.component.html',
  styleUrls: ['./bookappointment.component.css']
})


export class BookappointmentComponent implements OnInit {	
	
	full_name = new FormControl('');
	appointment_reason = new FormControl('');
	appointment_time = new FormControl('');
	
	loginForm: FormGroup = this.builder.group({
		full_name: this.full_name,
		appointment_reason: this.appointment_reason,
		appointment_time: this.appointment_time
	});

	constructor(private getViewAppintmentService : ViewappointmentService, private builder: FormBuilder, private route: ActivatedRoute, private router: Router ) { }

	ngOnInit() {
		  //createappointment
	}
  
    create_appointment(username,reason,booking_date){
		this.getViewAppintmentService.createData(username,reason,booking_date).subscribe(data =>{
			//console.log(data);
			if(data && data.result) {
				console.log(data.result);
				if(data.result){
					//self.router.navigate(['/home']);
					this.router.navigate(['/home']);
				}
			}
			
		});
	}
  
  register() {
	  if (this.loginForm.valid) {
		    // console.log(this.loginForm.value);
			this.create_appointment(
				this.loginForm.value.full_name,
				this.loginForm.value.appointment_reason,
				this.loginForm.value.appointment_time)
			}
  }

}

<h3>
  Book Appointment 
</h3>

<div class='appointment_form' >
<h2>Enter Appointment Details</h2>

<form [formGroup]="loginForm" (ngSubmit)="register()">

<div class='row'>
<div class='label'>Full Name</div>
<div class='input_field '><input type='text' required [formControl]="full_name"  id='full_name' name='full_name' >

</div>
</div> <!-- row -->

<div class='row'>
<div class='label'>Select Date and Time</div>
<div class='input_field'><input type='text'  [formControl]="appointment_time" name="appointment_time" id='appointment_time' value="2018-09-26 03:53"></div>

</div> <!-- row -->

<div class='row'>
<div class='label'>Reason of Appointment</div>
<div class='input_field'><textarea rows='9' cols='50' required [formControl]="appointment_reason"  id='appointment_reason' name='appointment_reason' ></textarea></div>

</div> <!-- row -->

<div class='row'>
<div class='label'>&nbsp;</div>
<div class='input_field form_update'>
	 <button type="submit">Submit</button>
</div>
</div> <!-- row -->


</form>

</div> <!-- appointment_form -->
